### ISSUE TITLE
Releasing to the Snap Store

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#27]
Please release this app to the Snap store.
https://snapcraft.io/docs/releasing-to-the-snap-store
Thanks.

**Comment by Lunarequest** [comment]
I have found snap to be falling behind consistently in terms of distribution support along with a wealth of problems that exist in it. hence I will not be supporting it. in case anyone is wondering here's a list of issues.

1. does not have any security with any distribution that ship's selinux over apparmor(even debian the older distro in currently working towards making selinux default). Lack of security on any distro that doesn't ship with ubuntu's patches for apparmor which has resulted in more distros not being able to use snaps security. 
2.  many distros (eg archlinux and opensuse) do not ship snap in their repos due to many issues caused by snapd
3. flatpak's have created portals which have allows sandboxing with user consent to exposed folders and various other things without portals and configurable permissions.
4. snap has been more or less replaced by flatpak by any distro. it has more applications better integration and the only group that has backed it is canonical. this is compared to flatpak which is backed by everyone else.

**Comment by xmha97** [comment]
Thank you for your explanation
I did not know the points you said
