### ISSUE TITLE
Fix tabs titles

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#36]
There is a small bug in the tabs titles.

The file name is "03. DevOps.pdf"

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/f9ba0252-4b87-455e-8b0a-08d3d26e45b5)

But in tab displayed: "DevOps.pdf .03"

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/6af0e176-8250-48cd-9669-52e1e71e180f)

**Comment by zeyus** [comment]
That's an odd one haha, shouldn't be too difficult to fix

**Comment by xmha97** [comment]
Does this problem happen to you too?

**Comment by zeyus** [comment]
> Does this problem happen to you too?

Yes. I just hadn't loaded any PDFs that had additional `.`'s in them, I believe it's due to the way the `parse().base` is handled in the `path` module, it probably just splits on the `.` in the filename. I'll have to look into it but it's going to be something like that.

**Comment by zeyus** [comment]
Ok I'm pushing a fix, it's even sillier than that. It's literally because of the css using `rtl` (to make sure the end of the filename is displayed if it's a really really long name) and that punctuation in `rtl` switches around (obviously this is useful for Arabic and other RTL languages, but in this case, it was the source of the bug).

**Comment by xmha97** [comment]
Ok, thanks 🙏

**Comment by xmha97** [comment]
Thanks 🙏
